name: 'VRolePlay'
main: 'me.vahelce.vroleplay.VRoleplay'
version: '1.0-SNAPSHOT'
author: 'vahelce'

permissions:
  vroleplay.try:
    description: "Allow to use /try command"
  vroleplay.me:
    description: "Allow to use /me command"

commands:
  try:
    permission: "vroleplay.try"
  me:
    permission: "vroleplay.me"