name: 'VRolePlay'
main: 'me.vahelce.vroleplay.VRoleplay'
version: '2.0-SNAPSHOT'
author: 'vahelce'

permissions:
  vroleplay.try:
    description: "Allow to use /try command"
  vroleplay.me:
    description: "Allow to use /me command"
  vroleplay.do:
    description: "Allow to use /do command"
  vroleplay.ooc:
    description: "Allow to use OOC chat"
  vrolepaly.mask:
    description: "Allow to use masks"

commands:
  try:
    permission: "vroleplay.try"
  me:
    permission: "vroleplay.me"
  do:
    permission: "vroleplay.do"
  b:
   permission: "vroleplay.ooc"
  mask:
    permission: "vroleplay.mask"